FROM tomcat:8.5-jdk17-temurin

# Delete existing ROOT folder
#RUN ["rm", "-rf", "/usr/local/tomcat/webapps"]
#RUN ["mv", "/usr/local/tomcat/webapps.dist/", "/usr/local/tomcat/webapps"]
#RUN ["rm", "-rf", "/usr/local/tomcat/webapps/ROOT"]